server:
#  context-path: /${spring.application.name}
  tomcat:
    accesslog:
      enabled: false
  port: 8080

spring:
  application:
    name: search-rules-service
  cache:
    type: none
  profiles:
    active: local
  output:
    ansi:
      enabled: ALWAYS
  jackson:
    default-property-inclusion: non_null
  cloud:
    config:
      allow-override: true
      override-none: false
      fail-fast: true
      override-system-properties: false
      enabled: false
  sleuth:
    web:
      enabled: true
    sampler:
      percentage: 100
  zipkin:
    base-url: http://localhost:8680/
    flush-interval: 15
    enabled: false
  data:
    mongodb:
      uri: mongodb://freshdapp01v2.ftdi.com:27017/searchrules

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate : DEBUG


service:
  ruleStatusList:
    - active
    - inactive
  ruleReloadRate: 180000
  metrics:
    dropwizard:
      enabled: true
    prometheus:
      enabled: true
    jmx:
      enabled: true
  git:
    enabled: true
  swagger:
    enabled: true
  logging:
    enabled: true



#management:
#  security:
#    enabled: false
#
#hystrix:
#  command:
#    helloCommandKey:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000
#      circuitBreaker:
#        requestVolumeThreshold: 4
#        sleepWindowInMilliseconds: 60000
#      metrics:
#        rollingStats:
#          timeInMilliseconds: 180000
#  threadpool:
#    helloThreadPoolKey:
#      coreSize: 30
#      metrics:
#        rollingStats:
#          timeInMilliseconds:18000

