package com.micro.services.search.rules.search

import com.micro.services.search.api.request.SearchServiceRequest;
import com.micro.services.search.api.response.SearchServiceResponse;


rule "RedirectFlower"
    dialect "java"
    when
        req : SearchServiceRequest( q == "flowers" )
        res : SearchServiceResponse()
    then
        modify (res ) { setRedirect( "http://abc.com/flowers-cat/roses" ) };

end


