package droolsexample

import com.services.micro.rules.search.bl.impl.RulesServiceImpl.Message;

global java.util.List list




rule "GG World"
    dialect "mvel"
    when
        m : Message( status == Message.GOODBYE, message : message )
    then
        System.out.println( message );
    modify ( m ) { message = "Goodbye cruel world CHANGEDD........",
                   status = Message.HELLO };
end
