---
apiVersion: v1
kind: Service
metadata:
  name: search-rules-service-group
  labels:
    app: search-rules
spec:
  ports:
  - port: 8070
    targetPort: 8080
    name: server
  selector:
    app: search-rules
    ns: group
  type: ClusterIP