---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: search-rule-service-group
  labels:
    app: search-rule
    ns: group
spec:
  selector:
    matchLabels:
      app: search-rule
      ns: group
  replicas: 1
  template:
    metadata:
      labels:
        app: search-rule
        ns: group
    spec:
      containers:
      - name: search-rule-service
        imagePullPolicy: Always
        image: "gcr.io/deep-thought-185318/rule-service:latest"
        resources:
          requests:
            memory: "0.5Gi"
            cpu: "0.5"
        ports:
        - containerPort: 8080
          name: server
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "group"
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb-1-server-1:27017/searchrules"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: "api/rules/query?environment=t"
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10